# Generated by Django 4.1.7 on 2023-04-03 17:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100, null=True, unique=True)),
                ('address', models.TextField(default='')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2023, 4, 3, 23, 6, 25, 111480))),
                ('url', models.URLField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('field_of_study', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='profile_pics')),
                ('about_me', models.TextField(default='', null=True)),
                ('skills', models.TextField(default='', null=True)),
                ('certificates', models.TextField(default='', null=True)),
                ('highschool', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('transcript', models.FileField(null=True, upload_to='')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
