# Generated by Django 4.1.7 on 2023-04-03 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 23, 6, 44, 808777)),
        ),
    ]
