# Generated by Django 4.1.7 on 2023-04-03 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_university_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 23, 17, 25, 435942)),
        ),
    ]
