# Generated by Django 4.1.7 on 2023-04-03 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_student_field_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about_me',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='certificates',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='highschool',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='university',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 23, 31, 7, 822198)),
        ),
    ]
