# Generated by Django 4.1.7 on 2023-04-03 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_university_address_alter_university_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 1, 2, 42, 123171)),
        ),
    ]
