# Generated by Django 4.1.7 on 2023-04-03 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_university_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 2, 11, 22, 90158)),
        ),
    ]
