# Generated by Django 4.1.7 on 2023-04-03 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Shortlisted', 'Shortlisted'), ('Accepted', 'Accepted')], default='Waiting', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university')),
            ],
        ),
    ]
