# Generated by Django 4.1.7 on 2023-04-03 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_date',
            field=models.DateField(default=datetime.date(2023, 4, 4)),
            preserve_default=False,
        ),
    ]
